services:
  - type: web
    name: nightscout
    env: node
    buildCommand: ""
    startCommand: "node server.js"
    envVars:
      - key: MONGO_CONNECTION
        value: mongodb+srv://<user>:<pass>@cluster0.wevnwkc.mongodb.net/nightscout?retryWrites=true&w=majority&appName=Cluster0
      - key: API_SECRET
        value: SecretShahak
      - key: DISPLAY_UNITS
        value: mg/dl
      - key: ENABLE
        value: careportal devicestatus rawbg
