services:
  - type: web
    name: nightscout
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    buildFilter:
      paths:
        - ./**
    envVars:
      - key: MONGO_CONNECTION
        value: mongodb+srv://nightscout_user:2$W-T33gG$G-KM2@cluster0.wevnwkc.mongodb.net/nightscout?retryWrites=true&w=majority&appName=Cluster0
      - key: API_SECRET
        value: SecretShahak
      - key: DISPLAY_UNITS
        value: mg/dl
      - key: ENABLE
        value: careportal devicestatus rawbg
